
spring:
  profiles:
    group:
      development:
        - test_database

      production:
        - production_database


---
spring:
  config:
    activate:
      on-profile: production_database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password: 1234
server:
  port: 9091

  mybatis:

    # mapper.xml 파일이 위치할 패키지 경로를 입력
    mapper-location: classpath*:com/server/common/dao/mybatis/mapper/*.xml


---
spring:
  config:
    activate:
      on-profile: test_database
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path

  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:

    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/testDB2;MODE=MYSQL;DATABASE_TO_LOWER=TRUE # H2 접속 정보
    username: root  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: 1234 # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
